# backend/render.yaml
services:
  - type: web
    name: school-management-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-management-db
          property: connectionString
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: DEBUG
        value: false
      - key: BACKEND_CORS_ORIGINS
        value: '["https://student-management-three-kappa.vercel.app"]'
    autoDeploy: true

databases:
  - name: school-management-db
    region: oregon
    plan: free
    databaseName: school_management
    user: school_admin